baseURL = "https://www.asynet.es"
disableLanguages = ["Fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "Asynet Enterprise Services LTD"
[Languages.en]
contentDir = "content/english"
copyright = "copyright &copy; [Asynet Enterprise Services LTD](https://www.asynet.es) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About Us"
weight = 1
[[Languages.en.menu.main]]
URL = "services"
name = "Service"
weight = 2
[[Languages.en.menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[Languages.en.menu.main]]
URL = "team"
name = "Team"
weight = 4
[[Languages.en.menu.main]]
URL = "pricing"
name = "Pricing"
weight = 5
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 6
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[Languages.es]
contentDir = "content/spanish"
copyright = "copyright &copy; [Asynet Enterprise Services LTD](https://www.asynet.es) Todos los derechos reservados"
home = "Inicio"
languageCode = "es-es"
languageName = "Es"
weight = 3
[[Languages.es.menu.main]]
URL = "about"
pre = "#"
name = "Sobre Nosotros"
weight = 1
[[Languages.es.menu.main]]
URL = "services"
pre = "#"
name = "Servicios"
weight = 2
[[Languages.es.menu.main]]
URL = "portfolio"
pre = "#"
name = "Portfolio"
weight = 3
[[Languages.es.menu.main]]
URL = "team"
pre = "#"
name = "Equipo"
weight = 4
[[Languages.es.menu.main]]
URL = "pricing"
pre = "#"
name = "Precio"
weight = 5
[[Languages.es.menu.main]]
URL = "blog"
pre = "#"
name = "Blog"
weight = 6
[[Languages.es.menu.main]]
URL = "contact"
pre = "#"
name = "Contacto"
weight = 7
[[Languages.es.menu.main]]
URL = "https://richard.asynet.es"
pre = ""
name = "Richard"
weight = "8"
[Languages.fr]
contentDir = "content/french"
copyright = "copyright et copie; 2019 [gethugothemes] (https://gethugothemes.com) tous droits réservés"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[menu]
static = []
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analitycs_id = ""
logo = "images/logo.png"
post_share = true
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyC8DksB0mGuZfvSFpBLKIXkvL4IbL40HdM"
map_latitude = "51.52739712639149"
map_longitude = "-0.08900685907050085"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/fontawesome/all.css"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/favicon.png"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/Asynet-431461757192540"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://www.twitter.com/asynetes"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/asynet/"
